### ISSUE TITLE
Invisible text in About/Dialog with Windows 11 Contrast Themes

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#11]
Please support Windows 11 contrast themes
![image](https://user-images.githubusercontent.com/23485114/156886168-fa97c699-c7f2-4f28-bc22-896e087d2f41.png)
As you can see, the texts are not readable.

**Comment by JohnTHaller** [comment]
This appears to only affect the About window due to some text being set to text as opposed to clWindow. Is that what you're seeing?

**Comment by JohnTHaller** [comment]
Also affects the Dialog (uninstalling, do you want to close your apps on exit, etc)

**Comment by JohnTHaller** [comment]
Got both the About and Dialog fixed internally and working with this new theme style in Windows 11. Don't seem to be adverse affects otherwise. Sadly, the updater/app store and backup/restore won't fully support this as NSIS doesn't and I need to do some annoying hacks to ensure the headers and start/finish work with high contrast themes in older versions of Windows.

![AboutWindowFix](https://user-images.githubusercontent.com/8020860/156896199-81b466de-a14e-4ec2-ae8e-d5a71be838d6.jpg)

**Comment by xmha97** [comment]
Thanks.

**Comment by JohnTHaller** [comment]
Fixed in today's 21.1 release
